# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kmXyoghz4ho-xmnsjeTz2UjIGOuv0HDx

## DATOS
"""

import pandas as pd
import numpy as np

data = {
        "nombre": ["Hugo","Juan","Victor","Carlos","Luis",None],
        "edad": [18,28,None,33,26,23],
        "ciudad":["CDMX","Monterrey","GDL","cdmx","GDL","Mty"],
        "ingresos":["$12,500","$18,500","$15,000",None,"$22,000","$20,000"]
        }

"""## MANIPULACIÓN DE DATOS"""

#Nota: para importar un .csv se usa el:
#variable: pd.read_csv("NombreArchivo.csv")
df = pd.DataFrame(data)
df

"""## Qué es un DataFrame?

Es una tabla de datos: filas (registros) y columnas (variables).

"""

#Exploración de los datos
df.head()

#Si deseas ver las columnas puedes hacerlo con
df.columns

df.info()

df.describe(include="all")

df["edad"]

df[df["edad"] > 30]

print(df)
df[
    (df["edad"] > 18) &
    (df["ingresos"] != "$22,000") &
    (df["nombre"] != "Hugo")

]

#Uso de count(), mean(), sum(), fillna(), str.replace(), astype()
print(df["edad"].count()) #Son 6, pero 1 es None
print("\n")
print(df["edad"].mean()) #Promedio
print("\n")
print(df["edad"].sum()) #Suma
print("\n")
print(df["nombre"].fillna("Desconocido")) #Rellena los valores con el dato que gustes.
print("\n")
print(df["ingresos"].str.replace("$","").str.replace(",","").astype(float))
#str.replace reemplaza x simbolo por y
#.astype(tipo_de_dato) cambia el tipo de dato de tu columna

"""## Limpieza de datos


"""

df_clean = df.copy()
print(df_clean)
#Rellenar valores faltantes
df_clean["edad"] = df_clean["edad"].fillna(df_clean["edad"].mean())
df_clean["ingresos"] = df_clean["ingresos"].fillna("$0")
df_clean["nombre"] = df_clean["nombre"].fillna("Desconocido")
df_clean

df_clean["ciudad"] = (
    df_clean["ciudad"]
    .str.lower() # Todo en minusculas o upper para mayusculas
    .str.strip() # Quitar espacios
)

# Con los datos limpios podemos trabajar con ellos
# 1) Saca los nombres de todos
# 2) Saca los nombres de todos sin los que digan desconocidos
# 3) Saca la cantidad de personas que hay por medio de ciudad
# Ahora pondremos uno un poco  más dificil
#4) Saca todos los datos donde no se muestren los que son de monterrey en ciudad y donde no se muestre los ingresos que sean $0
#5) Saca la edad promedio de las personas que no son de la ciudad de cdmx que ganan mayor o igual que $10,000

# 1)
df_clean["nombre"]

#1)
df_clean["nombre"]

#2)
df_clean[df_clean["nombre"] != "Desconocido"]["nombre"]

#3)
df_clean["ciudad"].count()

#4)
df_clean[(df_clean["nombre"] != "Desconocido") & (df_clean["ciudad"] != "monterrey") & (df_clean["ingresos"] != "$0")]

#5)
df_clean[(df_clean["ciudad"] != "cdmx") & (df_clean["ingresos"] != "$10,000")]["edad"].mean()

#Limpiar una ultima vez el DataFrame inicial para iniciar con Regresión Lineal
df["ingresos"].str.replace("$","").str.replace(",","").astype(float)

"""## Introducción a la Regresión Lineal"""

from sklearn.linear_model import LinearRegression

"""## Qué es una regresión lineal?

Una regresión intenta predecir un valor númerico a partir de otros datos.

Ejemplo:
-Predecir ingresos según edad.
-Predecir precio según tamaño

Aqui usaremos regresión lineal: el tipo más simple.
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.regplot(x = df_clean["edad"], y = df_clean["ingresos"])
plt.xlabel("Edad")
plt.ylabel("Ingresos")
plt.title("Relación entre Edad e Ingresos")
plt.show()

#MATRIZ DE CORRELACIÓN
#df_clean.corr()
df_clean[["edad", "ingresos"]].corr()

# 0.0 -> nada de relación
# 0.3 -> correlación débil
# 0.5-0.7 -> correlación moderada
# >0.8 -> correlación fuerte

x = df_clean[["edad"]]
y = df_clean[["ingresos"]]
print(x)
print(y)
modelo = LinearRegression()
modelo.fit(x,y)

"""Tiene relación con la forma de la pendiente.
Que hace fit? Busca los valores de m y b que mejor se ajustan a tus datos.
Minimiza el error entre los ingresos reales y los ingresos predichos.
y = mx+b

"""

edad_nueva = [[30]]
prediccion = modelo.predict(edad_nueva)
prediccion

#Podemos evaluar el modelo
from sklearn.metrics import r2_score, mean_squared_error
y_pred = modelo.predict(x) # Son los ingresos que el modelo cree según la edad.
#ingresos = B0 + B1 * edad
#B0 -> Intercepto
#B1 -> Coeficiente de edad

r2 = r2_score(y, y_pred)
# 0.3 - 0.5 es aceptable, pero es mejor tener un modelo 0.6 - 0.8 o muy bueno con > 0.8

mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)
print(r2)

#Regresión Logistica se suele usar -> Accuracy,Precision, F1 Score, Recall, Roc Auc