# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sUXyigeLLAVosFmuu6lsry66v9qeonan

## FUNCIONES
"""

def mensaje():
  print("Hola")

mensaje()

#Función con retorno
def mensaje():
  return "Hola"
va = mensaje()
print(va)

def saludo(Nombre):
  print("Hola, como estas?", Nombre, "!!")

TuNombre = input("Ingresa tu Nombre: ")
saludo(TuNombre)
  # Nombre de la variable del parametro puede o no ser el mismo fuera de la función

saludo("Grupo")

def suma(numero_1, numero_2):
  return numero_1 + numero_2

suma = suma(1,2)
print(suma)

def bienvenida(nombre = "invitado"):
  print("Hola", nombre)
bienvenida()
bienvenida("Hugo")

def suma(numero_1 = 2, numero_2 = 10):
  return numero_1 + numero_2

suma = suma(61,70)
print(suma)

#Descuento
def descuento(precio, desc = 0.15):
  precio = precio * (1 - desc)
  print("El nuevo precio es: ",precio)
descuento(750)
descuento(900,0.10)

def usuario(nombre,edad):
  return (nombre,edad)
persona = usuario("Hugo",18)
print(persona)

# Listas = [], tuplas = (), sets = {}
def operaciones(numero):
  doble = numero * 2
  triple = numero * 3
  cuadruple = numero * 4
  quintuple = numero * 5
  return doble, triple, cuadruple, quintuple
resultado = operaciones(4)
print(resultado)

"""## Funciones que llaman a otras funciones"""

def saludar(nombre):
  return f"Hola, {nombre}!"

def despedirse(nombre):
  return f"adios, {nombre}!"
def mensaje_completo(nombre):
  saludo = saludar(nombre)
  despedida = despedirse(nombre)
  return saludo + "\n" + despedida

print(mensaje_completo("Hugo"))

#Tenemos una heladeria
def pedir_sabor():
  sabores = ["vainilla", "chocolate", "fresa"]
  print("Sabor disponible", "\n", sabores)
  #.lower() hace minusculas
  #.strip() hace espacios
  sabor = input("Elige un sabor: ").strip().lower()

  while sabor not in sabores:
    sabor = input("Elige un sabor (nuevamente): ").strip().lower()
  return sabor

  def pedir_cantidad():
    cantidad = int(input("Cuantas bolas de nieve?: "))
    while cantidad <= 0:
      cantidad = int(input("Cuantas bolas de nieve? (Ingresa un valor válido): "))
    return cantidad

#Función Madre (Llama a otras)
def pedir_helado():
  sabor = pedir_sabor()
  cant = pedir_cantidad()
  print(f"Pedido: {cant} bola(s) de {sabor}")
  return cant, sabor

total_pedidos = int(input("Cuantos clientes atenderas?: "))
for i in range(total_pedidos):
  pedir_helado()

"""## Funciones Lambda


"""

sumar = lambda x,y : x + y
print(sumar(2,3))

descuentoLambda = lambda desc, precio : ((precio * (1-desc), precio * desc))
nuevoprecio = descuentoLambda(0.4,500)
print("El precio a pagar es: ", nuevoprecio[0], ", el descuento que se hizo fue de: ", nuevoprecio[1])

"""## Errores (excepciones)

"""

try:
  dividendo = float(input("Ingresa el dividendo:"))
  divisor = float(input("Ingresa el divisor: "))
  division = dividendo / divisor
except ZeroDivisionError:
  print("Error: el divisor no debe ser 0")
except ValueError:
  print("Error: Ingrese un valor numerico")

try:
  numero = int(input("Escribe un numero:"))
  print(numero)
except ValueError:
  print("Ingrese un valor numerico")

def suma(a, b):
    return a + b

def resta(a, b):
    return a - b

def producto(a, b):
    return a * b

def division(a, b):
    if b == 0:
        return "Error: no se puede dividir entre 0"
    return a / b

def potencia(a, b):
    return a ** b

def menu():
    while True:
        print("\nMi calculadora\n")
        print("1. Suma")
        print("2. Resta")
        print("3. Producto")
        print("4. División")
        print("5. Potencia")
        print("6. Salir")

        try:
            op = int(input("Seleccione una opción: "))
        except ValueError:
            print("Ingrese un número válido")
            continue

        if op == 6:
            print("Saliendo...")
            break

        if op < 1 or op > 6:
            print("Opción no válida")
            continue

        try:
            a = float(input("Ingrese el primer número: "))
            b = float(input("Ingrese el segundo número: "))
        except ValueError:
            print("Ingrese un número válido")
            continue

        if op == 1:
            print("Resultado:", suma(a, b))
        elif op == 2:
            print("Resultado:", resta(a, b))
        elif op == 3:
            print("Resultado:", producto(a, b))
        elif op == 4:
            print("Resultado:", division(a, b))
        elif op == 5:
            print("Resultado:", potencia(a, b))

# Ejecutar la calculadora
menu()