# -*- coding: utf-8 -*-
"""Copia de Te damos la bienvenida a Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8xN-nVgkQU5fWY0tIHByRgT1_k3q2Eh
"""

enteros = 4
float = 3.9
type(float)

caracteres = "a"
string = "Hey, que onda"
type(string)

falso = False # falso es 0
verdadero = True # verdadero es 1

#Imprimir
print(float)

name = input("Mi nombre es:") #lo guarda como string
print(name)

num = int(input("Ingresar un numero: "))
print(num + 1)

print(3+4)
variable1,variable2 = 20,40
print(variable1+variable2)

print(2-5)
v1 = 10.4
v2 = 4
result = v2 - v1
print(result)

M1,M2 = 2,3.14
print(M1 * M2)

print(M1 / M2)

print(M2 // M1)

print( 6/2 * 3)

#Potencias

print(2 ** 3)
p1,p2 = 7,2
print(p1 ** p2)

# Área de un Circúlo
pi = 3.14
r = 4
A = pi * (r**2)
A

HM = "Hola mundo"
print(HM)

a,b = "ta", "co"
print(a+ " " +b)
print(a+b)

Animal = "pez"
Nombre = "pecesillo"
Fruta = "Hojuelas"
Profesion = "Nadar"

print(f"Hola soy {Nombre} y soy un {Animal}, me gustan las {Fruta} y me dedico a {Profesion}.")

# <,>, <=, >=, and, or (SIEMPRE RETORNA UN BOOLEANO)
b1 = 4 > 5
b2 = 7 > 3
b3 = 14 >= 14
b3

#Quieres un sandwich con todo
pan = True
queso = True
mayonesa = True
jamon = False
print(pan and queso and mayonesa or jamon)

print(True * 20)
print(False * 20)