# -*- coding: utf-8 -*-
"""Copia de Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CaSBxxwiROeqA2jCOdDqnfaEOpvSLU7x

# Estructuras de datos

Listas = ordenadas, modificadas, permiten duplicados.

Tuplas = ordenadas, inmutables, permiten duplicados.

Sets = no ordenados, sin duplicados.

Diccionarios = pares clave: valor.

Nota:
Pilas (FILO = First in, last out)

Colas (FIFO = First in, First out)


Listas enlazadas (o doblemente enlazadas)
"""

lista_de_compras = ["platanos","manzana","piña","huevos","mantequilla","queso"]
print(lista_de_compras)

print(lista_de_compras[1])

# Agregar un elemento a la lista

lista_de_compras.append("leche")
lista_de_compras

# Agregar un elemento en una posición específica

lista_de_compras.insert(1,"naranjas")
lista_de_compras

print(lista_de_compras)

# Para eliminar un elemento de una lista existe el remove y el pop

lista_de_compras.remove("platanos")
print(lista_de_compras)

# Podemos recorrer el arreglo por medio de un for
va = "Python"
va[3]

for elemntos in lista_de_compras:
  print(elemntos)

# len() saca el tamaño de la lista
print(len(lista_de_compras))
for i in range(len(lista_de_compras)):
  print(f"{i + 1} - {lista_de_compras[i]}")

promedios = [55.6,89.5,23.6,97.5,72.4,100]
promedios.sort() #sort() sirve para ordenar la lista de manera ascendete
print(promedios)

# ordenar de manera descendente
promedios.sort(reverse=True)
print(promedios)

# Podemos ingresar al ultimo elemento de una lista
print(promedios[-2])

# Encontrar el mayor y el menor de una lista
print(max(promedios))
print(min(promedios))

#Declaración y uso de matrices
calificaciones = [[100,88,93],[99,56,72]]
i = 1
for cali_i in calificaciones:
  print(f"\nAlumno {i}")
  j = 1
  for cali_j in cali_i:
    print(f" Cali {j}: {cali_j}")
    j += 1
  j= 0
  i += 1

"""## TUPLAS

Colecciones ordenadas pero inmutables.
"""

# Hagamos una donde guardemos fechas de nacimientos de un grupo en una tupla
fechas = ("31/08/07","07/07/07","25/12/25")
print(type(fechas))
fechas

fecha_lista = list(fechas)

"""## SETS

Los sets son colecciones sin orden y que no permiten elementos duplicados.
"""

nombres = {"Hugo","Marian","Melisa","Jacky"}
print(nombres)
print(type(nombres))

distintos_datos = {"Hugo","Marian","Melisa","Jacky",1,9}
distintos_datos

#Add
nombres.add("Victor")
nombres

#Union
matutino = {20322,22183,2309032,120120}
vespertino = {203322,2312313,42343,2324}
total_matriculas = matutino.union(vespertino)
print(total_matriculas)

# Intersección
ca = {1234,1212,32132,13231,23132,123213,545,54553}
al = {1234,324342,324342,32436}

ca_al = ca & al
print(ca_al)

# Diferencia
solo_calculo = ca.difference(al)
print(solo_calculo)

nombres = {"Hugo","Marian","Melisa","Jacky"}
nombres.remove("Melisa")
print(nombres)

#Eliminar todo el SET
nombres.clear()
nombres

"""## DICCIONARIOS

Los diccionarios son colecciones no ordenadas de pares clave:valor.
"""

alumno = {
    "nombre": "Hugo Renne",
    "Edad": 18,
    "carrera": "IB",
    "semestre": 1,
    "promedio": 91,
    "calificaciones": [100,93,89,90,92]
}
print(type(alumno))
alumno

# Agregar al diccionario
alumno["area preferida"] = "Cálculo"
alumno

for valor in alumno:
  print(alumno[valor])

for clave, valor in alumno.items(): # devuelve una vista de todos los pares clave:valor del diccionario
 print(clave,": ", valor)

# El método .clear() también usar aqui.
# Tenemos el .get que nos ayuda a obtener el valor de cierta clave
print(alumno.get("semestre"))

if "carrera" in alumno:
  print("Existe carrera")
else:
    print("No existe carrera")

if("dinero") in alumno:
  print("Alumno tiene dinero")
else:
  print("Alumno no tiene dinero")

alumno.update({"semestre":4})
alumno