# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1udypAO1HiUXGMT3K5trwoY6eZ-2ciRbd

## Que es POO y por qué usarla?

1. Clases:
Una clase es como el molde o plano para crear algo.

2. Objetos:
Un objeto es una instancia real tangible creada a partir de una clase.

Entidades: Clases y Objetos.
"""

class Perro: # Creaste tu clase
  def ladrar(self): # Método
    print("Guau!")

mi_perro = Perro()
mi_perro.ladrar()

"""self, init y el ciclo de vida de un objeto."""

class Perro:
   def __init__(self, nombre, edad): #Constructor
     self.nombre = nombre
     self.edad = edad
   def presentarse(self):
     print(f"Soy {self.nombre} y tengo {self.edad} años")
tyson = Perro("Tyson", 3)
tyson.presentarse()
#__init__ python llama a crear el objeto.

# Atributos: de instancia vs de clase
class Perro:
  patas = 4
  especie = "Caninis Familiaris" # Atributos de clase
  def __init__(self,nombre):
    self.nombre = nombre # Atributos de instancia
p1 = Perro("Tyson")
p2 = Perro("Firulais")
print(p1.especie)
print(p2.especie)
print("\n")
p2.especie = "Gato"
print(p1.especie)
print(p2.especie) # Cambió el atributo de la clase para p2.

"""## Métodos: De instancia, clase

Un método de instancia es una función definida dentro de una clase que:
-Opera sobre un objeto concreto
-Puede acceder y modificar los atributos de ese objeto
-Recibe como primer parametro a self.

"""

class tuclase:
  def metodo(self):
    pass

class calculadora:
  def __init__(self, num1, num2):
    self.num1 = num1
    self.num2 = num2
  def sumar(self):
    print(self.num1 + self.num2)
  def resta(self):
    print(self.num1 - self.num2)
  def multiplicacion(self):
    print(self.num1 * self.num2)
  def division(self):
    if self.num2 == 0:
      print("Número no divisible")
    else:
      print(self.num1 / self.num2)
Calculadora = calculadora(7,3)
Calculadora.division()
Calculadora.multiplicacion()
Calculadora.sumar()

# Crear una clase animal, donde tenga una instancia de por lo menos 3 variables con 1 método y crea 4 objetos.
class animal:
  def __init__(self,nombre,especie,patas,comida_fav,sonido):
    self.nombre = nombre
    self.especie = especie
    self.patas = patas
    self.comida_fav = comida_fav
    self.sonido = sonido

  def emitir_sonido(self):
    print(self.sonido)

gato = animal("Rayas","Gato",4,"Carne","Miau")
perro = animal("Tyson","Perro",4,"Pollo","Woof")
pajaro = animal("Paco","Perico",2,"Alpistle","pipipi")
vaca = animal("Manchas","Vaca",4,"Pasto","Muuu")

perro.emitir_sonido()
gato.nombre = "Juan"
gato.nombre

"""## Encapsulamiento y propiedades"""

class Cuenta:
  def __init__(self,saldo):
    self._saldo = saldo
# Sirve para proteger los datos internos de un objeto y controlar como se leen o modifican.
cuenta = Cuenta(1000)
cuenta.Cuenta = 2000

# Getters y Setters
class Cuenta:
  def __init__(self,saldo):
    self.__saldo = saldo
  @property
  def saldo(self): #Getter
  #Permite leer el valor de _Saldo usando c.saldo
    return self.__saldo
  @saldo.setter #Setter
  def saldo(self,valor):
    self.__saldo = valor
c = Cuenta(200)
print(c.saldo)
c.saldo = 1000

"""## Herencia y Abstracción"""

class vehiculo: #clase padre
  def __init__(self,marca,modelo):
    self.marca = marca
    self.modelo = modelo
  def descripción(self):
    return f"{self.marca}:{self.modelo}"
  def mover(self):
    return "El vehiculo se está moviendo..."

class coche(vehiculo):  #(clase hija)
    def mover(self):
      return "El coche esta conduciendo"

class Moto(vehiculo):
  def mover(self):
    return "La moto avanza sobre dos ruedas"

coche2 = vehiculo("Toyota", "Corolla")
coche = coche("BYD", "Dolphin")
moto = Moto("Yamaha","R6")
print(coche.descripción())
print(coche2.mover())
print(moto.mover())

class persona:
  def __init__(self,nombre,edad):
    self.nombre = nombre
    self.edad = edad
  def presentarse(self):
    print(f"Hola, soy {self.nombre} y tengo {self.edad} años")

class estudiante(persona):
    def __init__(self,nombre,edad,carrera):
      super().__init__(nombre,edad)
      self.carrera = carrera
    def presentarse(self):
      super().presentarse()
      print(f"Estudio la carrera de {self.carrera}")

#Reutiliza el constructor de la clase padre (evita duplicar el código)
#Ejecuta el comportamiento base y lo extiende

est = estudiante("Hugo", 18, "Ingenieria Biomédica")
est.presentarse()

#Abstracción
class animal:
  def hablar(self):
    raise NotImplementedError
class gato(animal):
  def hablar(self):
    return "miau"

"""## Polimorfismo

Significa que diferentes objetos pueden responder al mismo mensaje(método) de forma distinta, siempre y cuando compartan interfaz común.

## Compiscion HAS-A

Estas componiendo un objeto grande usando otros objetos. Es un principio de POO donde:
-Una clase no hereda de otra, si no que contiene un objeto de esa otra clase.
"""

class Banco:
  def __init__(self,dinero):
    self.dinero = dinero
    def ver_total(self):
      print(f"Total en la cuenta: ${self.dinero}")

class persona:
  def __init__(self,cuenta: Banco): # Indica que este parametro deberia ser una instancia de la clase Banco.
    self.cuenta = cuenta # Persona tiene un banco, no hereda de el.

"""## Composición vs herencia

No significa que alguna sea mejor que otra simplemente que aveces una te puede convenir más que otra:

Herencia: un gato es un animal (no "un gato tiene un animal")

Composición: Una persona tiene una cuenta (no "una persona es un banco)

## Queremos modelar un pequeño sistema para vehiculos.
Habrá distintos tipos:
coche
moto
bicicleta

todos son vehiculos, por lo tanto comparten caracteristicas básicas, pero cada uno se mueve distinto, debes poner una clase llamada motor la cual use composición. Opcional: usa polimorfismo.
"""

class vehiculo:
  def __init__(self,marca):
    self.marca = marca

  def mover(self):
    raise NotImplementedError("Este método debe ser implementado.")

class motor:
  def __init__(self,caballos):
    self.caballos = caballos
  def potencia(self):
    return f"{self.caballos} HP"

class coche(vehiculo):
  def __init__(self,marca,caballos):
    super().__init__(marca)
    self.motor = motor(caballos)  #Composición

  def mover(self):
    return f"El coche {self.marca} acelera con motor de {self.motor.potencia()}"


class Moto(vehiculo):
  def __init__(self, marca, caballos):
    super().__init__(marca)
    self.motor = motor(caballos)
  def mover(self):
    return f"La moto {self.marca} avanza sobre dos ruedas con motor de {self.motor.potencia()}"

class bicicleta(vehiculo):
  def __init__(self, marca):
    super().__init__(marca)
  def mover(self):
    return f"La bicicleta {self.marca} avanza con pedaleo humano."

def probar_vehiculos(lista):
  for v in lista:
    print(v.mover())

vehiculos = [
    coche("Toyota", 150),
    Moto("Yamaha", 90),
    bicicleta("Trek")
]

probar_vehiculos(vehiculos)