# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11NEw5dvrEBhL9bdA2c9Zi0nCJmjL1vBA
"""

if 5>4:
  print("Si, es mayor")

# Los condicionales sirven para evaluar operadores logicos.
cafe = 50
leche_deslactosada = True
if leche_deslactosada:
  cafe += 30
print(f"A pagar: ${cafe}")

nota = float(input("Ingresa una nota:"))

if nota >= 70:
  print("Se acreditó la materia")
else:
  print("No se acreditó la materia")

edad = 12
if edad >= 18:
  print("Eres mayor")
  if edad >= 30:
    print("Eres adulto")
  else:
    print("Eres un adulto mayor")
else:
  print("Eres menor")
  if edad <= 12:
    print("Eres un niño")
  else:
      print("Eres un adolescente")

# Se preguntará la calificación del 0 al 100 y saber su equivalente en el sistema de E.E.U.U. Para simplicidad: A+ = 100, A = 99-90, B= 89-80, C= 79-70, D= 69-60, F = <60
cal = 98
if cal >= 0 and cal <= 100:
 if cal == 100:
  print("A+")
 elif cal >= 90:
  print("A")
 elif cal >= 80:
  print("B")
 elif cal >= 70:
  print("C")
 else:
  print("F")
else:
  print("error")

num = 9
if num % 3 == 0 or num % 5 == 0:
  print(f"El numero {num} es multiplo de 3 o 5")

# saber si el numero es par o impar
num = 4
if not num % 2 == 0:
  print(f"El numero {num} es impar")
else:
  print(f"El numero {num} es par")

for i in range(5):
  print(i)

for num in range (2,11):
  print(num)

cadena = "Que onda"
for letra in cadena:
  print(letra)

for i in range(2,21,3):
  print(i)

suma = 0
numeros = int(input("Ingresa el numero para sumar o 0 para salir:"))

while numeros != 0:
  suma += numeros
  numeros = int(input("Ingresa el numero para sumar o 0 para salir:"))
print(f"La suma es {suma}")

numero = 0
while numero <= 12:
  print(numero)
  numero += 1

