# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FNV4mAZsUn8nTZaAchpiWmtkhpfU_w4n

## INDICE

Modulos integrados:
math, random, string, datetime, os, sys, time, json.

Librerias externas: Numpy, request, Matplotlib.

## MODULO

Un modulo es una unidad de organización del codigo que permite encapsular y dividir el software en partes más manejables, generalmente representado como un archivo que contiene codigo relacionado, como funciones, variables o métodos de clase.

## MODULOS INTEGRADOS
"""

#Librerias por defecto en Python
import math
print(math.pi)

r = math.sqrt(4)
area = math.pi * r**2
print(f"r = {r:.4f}, area = {area:.2f}" )

import math as mate
print(mate.pi)
print("\n")
from math import pi, sqrt
print(pi)

#Libreria Random
#generacion de numeros pseudoaleatorios y muestreo ()
import random
nums = [random.randint(1,50) for _ in range(5)]
print(nums)

#Contraseña aleatoria de 12 caracteres
import random
import string

todos = string.ascii_letters + string.digits + string.punctuation
longitud = 12
password = "".join(random.choice(todos) for _ in range(longitud))
print(password)

# Libreria DateTime
from datetime import datetime, timedelta
hoy = datetime.now()
#print(hoy)
mañana = hoy + timedelta(days = 1)
print(hoy.strftime("%Y-%m-%d %H:%M"))
print(mañana.strftime("%Y-%m-%d %H:%M"))

#Abstracción portable del sistema operativo
import os
cwd = os.getcwd()
files = os.listdir(cwd)
print(cwd)
print(files)
print(len(files), "archivos en", cwd)

import sys
print("Version de Python: ", sys.version)

import time
start = time.perf_counter()
print(start)
end = time.perf_counter()
print(end)
print("Duración: ", end - start)

"""## LIBRERIAS EXTERNAS

pip install tu_libreria

python -m pip install tu_libreria

# IMPORTANTE

JSON es un formato para guardar y transmitir datos. Es muy en APIs, archivos de configuración y almacenamiento de información. {Se parece a un diccionario de Python, pero es solo texto}

Sirve para:
-Convertir objetos de python
-Texto JSON y también texto JSON -> objetos de python.

Se llama:
Serializar que es convertir un objeto de python en texto JSON.
Deserializar es lo opuesto.
"""

#json.dums(obj): Convierte un diccionario u objeto de Python en un string JSON
import json
obj = {"nombre":"Hugo","edad":18}
print(type(obj))
s = json.dumps(obj, ensure_ascii = False)
print(s)
print(type(s))

#json.loads(texto_json): Convierte un string JSON en un diccionario Python
restaurar = json.loads(s)
print(restaurar)
print(type(restaurar))

"""## NUMPY

Provee el tipo ndarray, operaciones vectorizadas, broadcasting, utilidades de álgebra lineal y funciones matematicas en arrays. Es la base sobre la que se apoyan muchas librereias cientificas en python.

El arreglo NUMPY no es igual a la lista de Python, este no puede tener diferentes tipos de datos en el mismo.
"""

import numpy as np
A = np.array([[1,2,3],[4,5,6]]) # 2,3
v = np.array([10,20,30]) # 3
print(A + v)

z = np.zeros((3,3)) # 3,3
print(z)
o = np.ones((2,4))
print(o)
r=np.random.rand(3,3)
print(r)

#Rangos númericos
nums = np.arange(0,10,2) # saca los valores entre 0 y 10 de 2 en 2
print(nums)
x = np.linspace(0,1,5) # saca 5 valores espaciados de manera "equitativa" entre 0 y 1
print(x)

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

print(a.dot(b)) # producto entre dos matrices
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[10,20],[30,40],[50,60]])
print(c.dot(d))

data = np.array([1,2,3,4,5])
print(data.min())
print(data.max())
print(data.sum())
print(data.mean())
print(data.std())

A = np.array([1,6,3,9,2])
print(A[A > 5])

"""## MATPLOTLIB"""

import matplotlib.pyplot as plt

"""#### GRÁFICA DE LINEAS"""

x = [1,2,3,4,5]
y = [2,3,5,7,11]
#linestyle, linewidth
plt.plot(x,y, marker = "x")
plt.title("Titulo de la gráfica")
plt.xlabel("Eje X")
plt.ylabel("Eje Y")
plt.show()

#o un circulo
#. point
#, pixel
#x pone una x

"""####GRÁFICO DE DISPERSIÓN"""

import random
x = [random.randint(1,100) for _ in range(10)]
y = [random.randint(1,100) for _ in range(10)]
plt.scatter(x,y)
plt.title("Gráfico de puntos")
plt.xlabel("Eje X")
plt.ylabel("Eje Y")
plt.show()